import Head from 'next/head'
import CrudContainer from '../containers/CrudContainer'
export default function Home() {
  return (
    <>
      <Head>
        <title>maldita base de datos</title>
        <meta name="descripcion" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CrudContainer/>
    </>
  )
}
